### ISSUE TITLE
Make pacman

### ISSUE THREAD

**Issue by Nikitaodessa** [kladd/pacman-osx#10]
I've installed all packages by "brew" and libarchive is 3.1.2 and when I wanted to make pacman I have had an Error:

Making all in lib/libalpm
Making all in po
make[3]: Nothing to be done for `all'.
  CC       libalpm_la-add.lo
add.c:32:10: fatal error: 'archive.h' file not found
# include <archive.h>

```
     ^
```

1 error generated.
make[3]: **\* [libalpm_la-add.lo] Error 1
make[2]: **\* [all-recursive] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

///////////////////////////////////////////////////////////////////////

Also when I tried to PATH=$HOME/pacman-deps/bin:$PATH ./build/autogen.sh, I have had :

99% tests passed, 2 tests failed out of 149

Total Test time (real) =  17.21 sec

The following tests FAILED:
     81 - libarchive_test_write_compress_lzma (Failed)
     83 - libarchive_test_write_compress_xz (Failed)
Errors while running CTest
make[2]: **\* [test] Error 8
make[1]: **\* [distcheck-hook] Error 2
make: **\* [distcheck] Error 1

**Comment by kladd** [comment]
The first problem is caused by libarchive's `archive.h` not being in the include path, which should be taken care of by the `export LIBARCHIVE_CFLAGS="-I${HOME}/pacman-deps/include"` line in the pacman compile steps.

That second message is no problem. If you continue with the steps for libarchive

```
./configure --prefix=$HOME/pacman-deps
make
make install
```

you should end up with `archive.h` in $HOME/pacman-deps/include

**Comment by kladd** [comment]
Also, compiling it earlier I ran into an issue with a missing openssl header. If you installed with brew you may want to add that include path (`export LIBSSL_CFLAGS="-I/usr/local/opt/openssl/include"`) to the environment as well:

```
export LIBARCHIVE_CFLAGS="-I${HOME}/pacman-deps/include"
export LIBARCHIVE_LIBS="-larchive"
export LIBCURL_CFLAGS="-I/usr/include/curl"
export LIBCURL_LIBS="-lcurl"
export LIBSSL_CFLAGS="-I/usr/local/opt/openssl/include"

./configure --prefix=/usr/local \
            --enable-doc \
            --with-scriptlet-shell=/usr/local/bin/bash \
            --with-curl
make
make -C contrib
make install
make -C contrib install
```

**Comment by Nikitaodessa** [comment]
I have tried in this way
https://drive.google.com/file/d/0BxN_YVo9hyKxY1RUN3E0LUl4cTg/view?usp=sharing

**Comment by Nikitaodessa** [comment]
Do you have something like youtube tutorial?

**Comment by kladd** [comment]
Looks like I missed another step, thanks for pointing that out. The `configure` script is generated by the `autogen.sh` script in the pacman directory. Also, since you're using brew to install the dependencies the libarchive path needs to be changed to `/usr/local/include` instead of the pacman-deps one.

``` bash
export LIBARCHIVE_CFLAGS="-I/usr/local/include"
export LIBARCHIVE_LIBS="-larchive"
export LIBCURL_CFLAGS="-I/usr/include/curl"
export LIBCURL_LIBS="-lcurl"
export LIBSSL_CFLAGS="-I/usr/local/opt/openssl/include"

./autogen.sh

./configure --prefix=/usr/local \
            --enable-doc \
            --with-scriptlet-shell=/usr/local/bin/bash \
            --with-curl
make
make -C contrib
make install
make -C contrib install
```

I don't have a video tutorial, I might be able to look into that. In the meantime it looks like my write up is missing some steps. I'll be sure to add those in.

**Comment by Nikitaodessa** [comment]
Autogen.sh doesn't have anything to patch. And also, how to change brew directory?

**Comment by kladd** [comment]
The directory thing is already changed in the code snippit in my last comment. What is the message that autogen.sh gives you?

**Comment by Nikitaodessa** [comment]
Choose file to patch:

**Comment by Nikitaodessa** [comment]
Those files wasn't found, that have to be patched

**Comment by kladd** [comment]
Do you see a not found message after `autoreconf` in the lines before `Choose file to patch`?

**Comment by Nikitaodessa** [comment]
Yes

**Comment by Nikitaodessa** [comment]
And also, by doing this tutorial you have made more for penetration testing on Mac than anybody else)

**Comment by Nikitaodessa** [comment]
MacBook-Pro-Nik:pacman nik$ ./autogen.sh
- autoreconf -i
  Can't exec "autopoint": No such file or directory at /usr/local/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 345.
  autoreconf: failed to run autopoint: No such file or directory
  autoreconf: autopoint is needed because this package uses Gettext
- patch -d build-aux -Np0 -i ltmain-asneeded.patch
  can't find file to patch at input line 3
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |--- ltmain.sh.orig 2013-06-26 14:31:53.472627840 +1000
  |+++ ltmain.sh  2013-06-26 14:30:56.137038936 +1000
  --------------------------
  File to patch:

**Comment by Nikitaodessa** [comment]
https://drive.google.com/file/d/0BxN_YVo9hyKxbVVOTGVaaGlqUUk/view?usp=sharing

**Comment by Nikitaodessa** [comment]
Help!!!!

**Comment by kladd** [comment]
```
~ » brew info gettext
gettext: stable 0.19.5.1 (bottled)
GNU internationalization (i18n) and localization (l10n) library
https://www.gnu.org/software/gettext/

This formula is keg-only.
OS X provides the BSD gettext library and some software gets confused if both are in the library path.

/usr/local/Cellar/gettext/0.19.4 (1920 files, 21M)
  Poured from bottle
/usr/local/Cellar/gettext/0.19.5.1 (1921 files, 22M)
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/gettext.rb
==> Dependencies
Build: xz ✔
==> Options
--universal
    Build a universal binary
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

OS X provides the BSD gettext library and some software gets confused if both are in the library path.
```

autopoint, the thing that your error message says you are missing, is part of the gettext package. Since you're using brew instead of compiling from source as I did in the tutorial, your paths are incorrect. To solve this, add the gettext bin path to your PATH variable, which should be something like this:

``` bash
export PATH=/usr/local/opt/gettext/bin:$PATH
```

Life gets in the way sometimes.
