### ISSUE TITLE
pacman-osx.sh doesn't complete

### ISSUE THREAD

**Issue by BBaysinger** [kladd/pacman-osx#12]
I ran pacman-osx.sh, and got this:

/Users/bradley/Documents/Work/bll_work/docs/pacman-osx.sh: line 92: pushd: /tmp/tmp.LjrJ3b/pkg-config-0.28: No such file or directory

**Comment by kladd** [comment]
Looks like the URL for pkg-config changed. I've updated it but it's probably not the only case of this. When I have some time later I'll test the rest of them. Thanks for opening the issue.
